/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CarruselCompo: typeof import('./src/components/CarruselCompo.vue')['default']
    HeaderApp: typeof import('./src/components/HeaderApp.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InstucionalApli: typeof import('./src/components/InstucionalApli.vue')['default']
    InstucionalApp: typeof import('./src/components/InstucionalApp.vue')['default']
    Login_Apli: typeof import('./src/components/Login/Login_Apli.vue')['default']
    LoginApp: typeof import('./src/components/LoginApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsuarioApp: typeof import('./src/components/UsuarioApp.vue')['default']
  }
}
